app:
  name: "app"
  mode: "dev"
  port: "8080"
mysql:
  host: ""
  port: 3306
  user: "root"
  password: ""
  dbname: "test"  
log:
  level: "debug"
  filename: "app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
redis:
  host: ""
  port: "6379"
  db: 0


  
